//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickitNewFace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TickitNewFace.Resources.Langue", typeof(Langue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour de la configuration.
        /// </summary>
        public static string Administration_MAJ_configuration {
            get {
                return ResourceManager.GetString("Administration_MAJ_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentation descriptions Ranges.
        /// </summary>
        public static string Alimentation_Descriptions_Ranges {
            get {
                return ResourceManager.GetString("Alimentation_Descriptions_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentation détails produits.
        /// </summary>
        public static string Alimentation_Details_Produits {
            get {
                return ResourceManager.GetString("Alimentation_Details_Produits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage de l&apos;application.
        /// </summary>
        public static string Alimentation_Parametrage {
            get {
                return ResourceManager.GetString("Alimentation_Parametrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentation des prix.
        /// </summary>
        public static string AlimentationPrix_MAJ_uploadFile {
            get {
                return ResourceManager.GetString("AlimentationPrix_MAJ_uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement fichier mise à jours Produits.
        /// </summary>
        public static string AlimentationProduits_MAJ_uploadFile {
            get {
                return ResourceManager.GetString("AlimentationProduits_MAJ_uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour directe d&apos;un Range.
        /// </summary>
        public static string AlimentationRange_MAJ_directe {
            get {
                return ResourceManager.GetString("AlimentationRange_MAJ_directe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement fichier mise à jours Ranges.
        /// </summary>
        public static string AlimentationRange_MAJ_uploadFile {
            get {
                return ResourceManager.GetString("AlimentationRange_MAJ_uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monter soi-même.
        /// </summary>
        public static string AMonterSoiMeme {
            get {
                return ResourceManager.GetString("AMonterSoiMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La capacité du chevalet est atteinte. Elle est limitée à 14 produits..
        /// </summary>
        public static string Chevalet_capaciteAtteinte {
            get {
                return ResourceManager.GetString("Chevalet_capaciteAtteinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression des reglettes limitee a 10 produits.
        /// </summary>
        public static string Chevalet_capaciteAtteinteReglette {
            get {
                return ResourceManager.GetString("Chevalet_capaciteAtteinteReglette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chevalet de gamme.
        /// </summary>
        public static string Chevalet_De_Gamme_Titre {
            get {
                return ResourceManager.GetString("Chevalet_De_Gamme_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi des produits de gammes différentes. Les chevalet est désormais de type vitrine.
        /// </summary>
        public static string Chevalet_gammeError {
            get {
                return ResourceManager.GetString("Chevalet_gammeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer chevalet vitrine.
        /// </summary>
        public static string Chevalet_ImprimerChevaletVitrine {
            get {
                return ResourceManager.GetString("Chevalet_ImprimerChevaletVitrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer réglette.
        /// </summary>
        public static string Chevalet_ImprimerReglette {
            get {
                return ResourceManager.GetString("Chevalet_ImprimerReglette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chevalet_ImprimerReglette653 {
            get {
                return ResourceManager.GetString("Chevalet_ImprimerReglette653", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer réglette carrée.
        /// </summary>
        public static string Chevalet_ImprimerReglettebis {
            get {
                return ResourceManager.GetString("Chevalet_ImprimerReglettebis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer chevalet de gamme.
        /// </summary>
        public static string Chevalet_ImrpimerChevaletGamme {
            get {
                return ResourceManager.GetString("Chevalet_ImrpimerChevaletGamme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce Produit est déja existant dans le chevalet.
        /// </summary>
        public static string Chevalet_produitDejaExistant {
            get {
                return ResourceManager.GetString("Chevalet_produitDejaExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce produit du chevalet de gamme.
        /// </summary>
        public static string Chevalet_supprimerProduit {
            get {
                return ResourceManager.GetString("Chevalet_supprimerProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDER CHEVALET.
        /// </summary>
        public static string Chevalet_Vider {
            get {
                return ResourceManager.GetString("Chevalet_Vider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etes vous sur de vouloir vider le chevalet ?.
        /// </summary>
        public static string ConfirmJS_question {
            get {
                return ResourceManager.GetString("ConfirmJS_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière démarque.
        /// </summary>
        public static string Derniere_Demarque {
            get {
                return ResourceManager.GetString("Derniere_Demarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range sauvegardé avec succès.
        /// </summary>
        public static string DescriptionRange_SaveSuccess {
            get {
                return ResourceManager.GetString("DescriptionRange_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuxième démarque.
        /// </summary>
        public static string Deuxieme_Demarque {
            get {
                return ResourceManager.GetString("Deuxieme_Demarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est connecté.
        /// </summary>
        public static string EtatConnexion {
            get {
                return ResourceManager.GetString("EtatConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien prix.
        /// </summary>
        public static string Fiche_AncienPrix {
            get {
                return ResourceManager.GetString("Fiche_AncienPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Fiche_BoutonEditer {
            get {
                return ResourceManager.GetString("Fiche_BoutonEditer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string Fiche_BoutonImprimer {
            get {
                return ResourceManager.GetString("Fiche_BoutonImprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description légale (DGCCRF).
        /// </summary>
        public static string Fiche_DGCCRF {
            get {
                return ResourceManager.GetString("Fiche_DGCCRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur.
        /// </summary>
        public static string Fiche_Hauteur {
            get {
                return ResourceManager.GetString("Fiche_Hauteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information générales.
        /// </summary>
        public static string Fiche_InformationsGenerales {
            get {
                return ResourceManager.GetString("Fiche_InformationsGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur.
        /// </summary>
        public static string Fiche_Largeur {
            get {
                return ResourceManager.GetString("Fiche_Largeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur.
        /// </summary>
        public static string Fiche_Longueur {
            get {
                return ResourceManager.GetString("Fiche_Longueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montage.
        /// </summary>
        public static string Fiche_Montage {
            get {
                return ResourceManager.GetString("Fiche_Montage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monter soi même.
        /// </summary>
        public static string Fiche_Montage_aMonterSoiMeme {
            get {
                return ResourceManager.GetString("Fiche_Montage_aMonterSoiMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ne pas monter soi même.
        /// </summary>
        public static string Fiche_Montage_aNePasMonterSoiMeme {
            get {
                return ResourceManager.GetString("Fiche_Montage_aNePasMonterSoiMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string Fiche_Plus {
            get {
                return ResourceManager.GetString("Fiche_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pourcentage.
        /// </summary>
        public static string Fiche_Pourcentage {
            get {
                return ResourceManager.GetString("Fiche_Pourcentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix actuel.
        /// </summary>
        public static string Fiche_PrixActuel {
            get {
                return ResourceManager.GetString("Fiche_PrixActuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Fiche_Statut {
            get {
                return ResourceManager.GetString("Fiche_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continu.
        /// </summary>
        public static string Fiche_Statut_continued {
            get {
                return ResourceManager.GetString("Fiche_Statut_continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinu.
        /// </summary>
        public static string Fiche_Statut_Discontinued {
            get {
                return ResourceManager.GetString("Fiche_Statut_Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Fiche_Volume {
            get {
                return ResourceManager.GetString("Fiche_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recherche.
        /// </summary>
        public static string Global_recherche {
            get {
                return ResourceManager.GetString("Global_recherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sauvegarder.
        /// </summary>
        public static string Global_sauvegarder {
            get {
                return ResourceManager.GetString("Global_sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les infos.
        /// </summary>
        public static string LesInfos {
            get {
                return ResourceManager.GetString("LesInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les plus.
        /// </summary>
        public static string LesPlus {
            get {
                return ResourceManager.GetString("LesPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string LibelleRechercheProduits {
            get {
                return ResourceManager.GetString("LibelleRechercheProduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de téléchargement.
        /// </summary>
        public static string MenuDownload {
            get {
                return ResourceManager.GetString("MenuDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien prix.
        /// </summary>
        public static string MenuImpression_AncienPrix {
            get {
                return ResourceManager.GetString("MenuImpression_AncienPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string MenuImpression_BoutonAnnuler {
            get {
                return ResourceManager.GetString("MenuImpression_BoutonAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer.
        /// </summary>
        public static string MenuImpression_BoutonCalculer {
            get {
                return ResourceManager.GetString("MenuImpression_BoutonCalculer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string MenuImpression_BoutonImprimer {
            get {
                return ResourceManager.GetString("MenuImpression_BoutonImprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MenuImpression_Date {
            get {
                return ResourceManager.GetString("MenuImpression_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarque locale.
        /// </summary>
        public static string MenuImpression_DemarqueLocale {
            get {
                return ResourceManager.GetString("MenuImpression_DemarqueLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demarque locale de type numerique.
        /// </summary>
        public static string MenuImpression_DemarqueLocaleTypeError {
            get {
                return ResourceManager.GetString("MenuImpression_DemarqueLocaleTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string MenuImpression_FormatImpression {
            get {
                return ResourceManager.GetString("MenuImpression_FormatImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de specifier le format d impression..
        /// </summary>
        public static string MenuImpression_FormatNonSpecifie {
            get {
                return ResourceManager.GetString("MenuImpression_FormatNonSpecifie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez cocher cette case au cas ou vous voulez indiquer un pourcentage de promotion spécifique.
        /// </summary>
        public static string MenuImpression_NoticeDemarqueLocale {
            get {
                return ResourceManager.GetString("MenuImpression_NoticeDemarqueLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau prix sera .
        /// </summary>
        public static string MenuImpression_nouveauPrix {
            get {
                return ResourceManager.GetString("MenuImpression_nouveauPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pourcentage de réduction.
        /// </summary>
        public static string MenuImpression_PourcentageRecution {
            get {
                return ResourceManager.GetString("MenuImpression_PourcentageRecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu d&apos;impression.
        /// </summary>
        public static string MenuImpression_TitreMenu {
            get {
                return ResourceManager.GetString("MenuImpression_TitreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquette unique.
        /// </summary>
        public static string MenuImpression_TypeEtiquette {
            get {
                return ResourceManager.GetString("MenuImpression_TypeEtiquette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo / Soldes.
        /// </summary>
        public static string MenuImpression_TypePromoSoldes {
            get {
                return ResourceManager.GetString("MenuImpression_TypePromoSoldes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression en masse.
        /// </summary>
        public static string MenuImpressionEnMasse {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imprimer en masse.
        /// </summary>
        public static string MenuImpressionEnMasse_BtnImpressionMasse {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse_BtnImpressionMasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Impression en masse.
        /// </summary>
        public static string MenuImpressionEnMasse_FieldsetImpressionMasseLegend {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse_FieldsetImpressionMasseLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Téléchargement du fichier d&apos;impression en masse.
        /// </summary>
        public static string MenuImpressionEnMasse_FieldsetUploadFileLegend {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse_FieldsetUploadFileLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de produits sélectionnés :.
        /// </summary>
        public static string MenuImpressionEnMasse_NombreDeProduits {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse_NombreDeProduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun produit ne correspond aux critères de sélection suivants.
        /// </summary>
        public static string MenuImpressionEnMasse_ProduitsInexistants {
            get {
                return ResourceManager.GetString("MenuImpressionEnMasse_ProduitsInexistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche Produits.
        /// </summary>
        public static string MenuRecherche {
            get {
                return ResourceManager.GetString("MenuRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nbre de colis..
        /// </summary>
        public static string NombreColis {
            get {
                return ResourceManager.GetString("NombreColis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ResultatsRecherche_Actions {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string ResultatsRecherche_Libelle {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix actuel.
        /// </summary>
        public static string ResultatsRecherche_Prix {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamme.
        /// </summary>
        public static string ResultatsRecherche_Range {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string ResultatsRecherche_Statut {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        public static string ResultatsRecherche_Variation {
            get {
                return ResourceManager.GetString("ResultatsRecherche_Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monter soi-même.
        /// </summary>
        public static string TickitDataManager_aMonterSoiMeme {
            get {
                return ResourceManager.GetString("TickitDataManager_aMonterSoiMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix à emporter.
        /// </summary>
        public static string TickitDataManager_PrixAEmporter {
            get {
                return ResourceManager.GetString("TickitDataManager_PrixAEmporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix livré.
        /// </summary>
        public static string TickitDataManager_PrixLivrer {
            get {
                return ResourceManager.GetString("TickitDataManager_PrixLivrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultime démarque.
        /// </summary>
        public static string Ultime_Demarque {
            get {
                return ResourceManager.GetString("Ultime_Demarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger fichier.
        /// </summary>
        public static string UploadFile_ChargerFichier {
            get {
                return ResourceManager.GetString("UploadFile_ChargerFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error format] : Le fichier sélectionné présente un mauvais format..
        /// </summary>
        public static string UploadFile_ErrorFormat {
            get {
                return ResourceManager.GetString("UploadFile_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Erreur ligne.
        /// </summary>
        public static string UploadFile_ErrorLigne {
            get {
                return ResourceManager.GetString("UploadFile_ErrorLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error fichier inexistant] : le fichier spécifé n&apos;existe pas.
        /// </summary>
        public static string UploadFile_FichierInexistant {
            get {
                return ResourceManager.GetString("UploadFile_FichierInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier téléchargé est vide.
        /// </summary>
        public static string UploadFile_FichierVide {
            get {
                return ResourceManager.GetString("UploadFile_FichierVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  n&apos;existe pas dans le réferentiel..
        /// </summary>
        public static string UploadFile_SkuInexistant {
            get {
                return ResourceManager.GetString("UploadFile_SkuInexistant", resourceCulture);
            }
        }
    }
}
