//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Descripti__Langa__182C9B23", "T_Langue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Langue), "Description_Dgccrf", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Description_Dgccrf), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Description__Sku__1920BF5C", "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Produit), "Description_Dgccrf", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Description_Dgccrf), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Descripti__Langa__1DE57479", "T_Langue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Langue), "Description_Plus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Description_Plus), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Description__Sku__1ED998B2", "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Produit), "Description_Plus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Description_Plus), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Libelle_P__Langa__2D27B809", "T_Langue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Langue), "T_Libelle_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Libelle_Produit), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Variation__Langa__0DAF0CB0", "T_Langue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Langue), "T_Variation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Variation), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Produit), "T_Libelle_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Libelle_Produit), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Prix__Sku__1367E606", "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Produit), "T_Prix", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Prix), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Produit__RangeId__0519C6AF", "T_Range", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Range), "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Produit), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "FK__Variation__Sku__0EA330E9", "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TickitNewFace.App_Data.Produit), "T_Variation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Variation), true)]
[assembly: EdmRelationshipAttribute("HDIProductDBModel", "Produit_Impression", "Format_Impression", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Format_Impression), "T_Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TickitNewFace.App_Data.Produit))]

#endregion

namespace TickitNewFace.App_Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NewTickitDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NewTickitDBEntities object using the connection string found in the 'NewTickitDBEntities' section of the application configuration file.
        /// </summary>
        public NewTickitDBEntities() : base("name=NewTickitDBEntities", "NewTickitDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewTickitDBEntities object.
        /// </summary>
        public NewTickitDBEntities(string connectionString) : base(connectionString, "NewTickitDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewTickitDBEntities object.
        /// </summary>
        public NewTickitDBEntities(EntityConnection connection) : base(connection, "NewTickitDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Description_Dgccrf> Description_Dgccrf
        {
            get
            {
                if ((_Description_Dgccrf == null))
                {
                    _Description_Dgccrf = base.CreateObjectSet<Description_Dgccrf>("Description_Dgccrf");
                }
                return _Description_Dgccrf;
            }
        }
        private ObjectSet<Description_Dgccrf> _Description_Dgccrf;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Description_Plus> Description_Plus
        {
            get
            {
                if ((_Description_Plus == null))
                {
                    _Description_Plus = base.CreateObjectSet<Description_Plus>("Description_Plus");
                }
                return _Description_Plus;
            }
        }
        private ObjectSet<Description_Plus> _Description_Plus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Format_Impression> Format_Impression
        {
            get
            {
                if ((_Format_Impression == null))
                {
                    _Format_Impression = base.CreateObjectSet<Format_Impression>("Format_Impression");
                }
                return _Format_Impression;
            }
        }
        private ObjectSet<Format_Impression> _Format_Impression;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Langue> Langue
        {
            get
            {
                if ((_Langue == null))
                {
                    _Langue = base.CreateObjectSet<Langue>("T_Langue");
                }
                return _Langue;
            }
        }
        private ObjectSet<Langue> _Langue;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Libelle_Produit> Libelle_Produit
        {
            get
            {
                if ((_Libelle_Produit == null))
                {
                    _Libelle_Produit = base.CreateObjectSet<Libelle_Produit>("T_Libelle_Produit");
                }
                return _Libelle_Produit;
            }
        }
        private ObjectSet<Libelle_Produit> _Libelle_Produit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prix> Prix
        {
            get
            {
                if ((_Prix == null))
                {
                    _Prix = base.CreateObjectSet<Prix>("T_Prix");
                }
                return _Prix;
            }
        }
        private ObjectSet<Prix> _Prix;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produit> Produit
        {
            get
            {
                if ((_Produit == null))
                {
                    _Produit = base.CreateObjectSet<Produit>("T_Produit");
                }
                return _Produit;
            }
        }
        private ObjectSet<Produit> _Produit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Range> Range
        {
            get
            {
                if ((_Range == null))
                {
                    _Range = base.CreateObjectSet<Range>("T_Range");
                }
                return _Range;
            }
        }
        private ObjectSet<Range> _Range;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Variation> Variation
        {
            get
            {
                if ((_Variation == null))
                {
                    _Variation = base.CreateObjectSet<Variation>("T_Variation");
                }
                return _Variation;
            }
        }
        private ObjectSet<Variation> _Variation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resultats_recherche> resultats_recherche
        {
            get
            {
                if ((_resultats_recherche == null))
                {
                    _resultats_recherche = base.CreateObjectSet<resultats_recherche>("resultats_recherche");
                }
                return _resultats_recherche;
            }
        }
        private ObjectSet<resultats_recherche> _resultats_recherche;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Description_Dgccrf EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDescription_Dgccrf(Description_Dgccrf description_Dgccrf)
        {
            base.AddObject("Description_Dgccrf", description_Dgccrf);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Description_Plus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDescription_Plus(Description_Plus description_Plus)
        {
            base.AddObject("Description_Plus", description_Plus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Format_Impression EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormat_Impression(Format_Impression format_Impression)
        {
            base.AddObject("Format_Impression", format_Impression);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Langue EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLangue(Langue langue)
        {
            base.AddObject("T_Langue", langue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Libelle_Produit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLibelle_Produit(Libelle_Produit libelle_Produit)
        {
            base.AddObject("T_Libelle_Produit", libelle_Produit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Prix EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrix(Prix prix)
        {
            base.AddObject("T_Prix", prix);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Produit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduit(Produit produit)
        {
            base.AddObject("T_Produit", produit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Range EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRange(Range range)
        {
            base.AddObject("T_Range", range);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Variation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVariation(Variation variation)
        {
            base.AddObject("T_Variation", variation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resultats_recherche EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresultats_recherche(resultats_recherche resultats_recherche)
        {
            base.AddObject("resultats_recherche", resultats_recherche);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="Description_Dgccrf")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Description_Dgccrf : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Description_Dgccrf object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="langageId">Initial value of the LangageId property.</param>
        public static Description_Dgccrf CreateDescription_Dgccrf(global::System.String sku, global::System.Int32 langageId)
        {
            Description_Dgccrf description_Dgccrf = new Description_Dgccrf();
            description_Dgccrf.Sku = sku;
            description_Dgccrf.LangageId = langageId;
            return description_Dgccrf;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LangageId
        {
            get
            {
                return _LangageId;
            }
            set
            {
                if (_LangageId != value)
                {
                    OnLangageIdChanging(value);
                    ReportPropertyChanging("LangageId");
                    _LangageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LangageId");
                    OnLangageIdChanged();
                }
            }
        }
        private global::System.Int32 _LangageId;
        partial void OnLangageIdChanging(global::System.Int32 value);
        partial void OnLangageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LegalDescription
        {
            get
            {
                return _LegalDescription;
            }
            set
            {
                OnLegalDescriptionChanging(value);
                ReportPropertyChanging("LegalDescription");
                _LegalDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LegalDescription");
                OnLegalDescriptionChanged();
            }
        }
        private global::System.String _LegalDescription;
        partial void OnLegalDescriptionChanging(global::System.String value);
        partial void OnLegalDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Descripti__Langa__182C9B23", "T_Langue")]
        public Langue Langue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "T_Langue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "T_Langue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Langue> LangueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "T_Langue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "T_Langue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Description__Sku__1920BF5C", "T_Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "T_Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "T_Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="Description_Plus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Description_Plus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Description_Plus object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="langageId">Initial value of the LangageId property.</param>
        /// <param name="plus">Initial value of the Plus property.</param>
        public static Description_Plus CreateDescription_Plus(global::System.String sku, global::System.Int32 langageId, global::System.String plus)
        {
            Description_Plus description_Plus = new Description_Plus();
            description_Plus.Sku = sku;
            description_Plus.LangageId = langageId;
            description_Plus.Plus = plus;
            return description_Plus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LangageId
        {
            get
            {
                return _LangageId;
            }
            set
            {
                if (_LangageId != value)
                {
                    OnLangageIdChanging(value);
                    ReportPropertyChanging("LangageId");
                    _LangageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LangageId");
                    OnLangageIdChanged();
                }
            }
        }
        private global::System.Int32 _LangageId;
        partial void OnLangageIdChanging(global::System.Int32 value);
        partial void OnLangageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Plus
        {
            get
            {
                return _Plus;
            }
            set
            {
                if (_Plus != value)
                {
                    OnPlusChanging(value);
                    ReportPropertyChanging("Plus");
                    _Plus = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Plus");
                    OnPlusChanged();
                }
            }
        }
        private global::System.String _Plus;
        partial void OnPlusChanging(global::System.String value);
        partial void OnPlusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Descripti__Langa__1DE57479", "T_Langue")]
        public Langue Langue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "T_Langue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "T_Langue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Langue> LangueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "T_Langue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Langue>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "T_Langue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Description__Sku__1ED998B2", "T_Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "T_Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "T_Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="Format_Impression")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Format_Impression : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Format_Impression object.
        /// </summary>
        /// <param name="format">Initial value of the Format property.</param>
        public static Format_Impression CreateFormat_Impression(global::System.String format)
        {
            Format_Impression format_Impression = new Format_Impression();
            format_Impression.Format = format;
            return format_Impression;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Format
        {
            get
            {
                return _Format;
            }
            set
            {
                if (_Format != value)
                {
                    OnFormatChanging(value);
                    ReportPropertyChanging("Format");
                    _Format = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Format");
                    OnFormatChanged();
                }
            }
        }
        private global::System.String _Format;
        partial void OnFormatChanging(global::System.String value);
        partial void OnFormatChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "Produit_Impression", "T_Produit")]
        public EntityCollection<Produit> Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produit>("HDIProductDBModel.Produit_Impression", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produit>("HDIProductDBModel.Produit_Impression", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Langue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Langue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Langue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Langue CreateLangue(global::System.Int32 id)
        {
            Langue langue = new Langue();
            langue.Id = id;
            return langue;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryCode
        {
            get
            {
                return _CountryCode;
            }
            set
            {
                OnCountryCodeChanging(value);
                ReportPropertyChanging("CountryCode");
                _CountryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryCode");
                OnCountryCodeChanged();
            }
        }
        private global::System.String _CountryCode;
        partial void OnCountryCodeChanging(global::System.String value);
        partial void OnCountryCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Descripti__Langa__182C9B23", "Description_Dgccrf")]
        public EntityCollection<Description_Dgccrf> Description_Dgccrf
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Description_Dgccrf>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "Description_Dgccrf");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Description_Dgccrf>("HDIProductDBModel.FK__Descripti__Langa__182C9B23", "Description_Dgccrf", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Descripti__Langa__1DE57479", "Description_Plus")]
        public EntityCollection<Description_Plus> Description_Plus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Description_Plus>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "Description_Plus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Description_Plus>("HDIProductDBModel.FK__Descripti__Langa__1DE57479", "Description_Plus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Libelle_P__Langa__2D27B809", "T_Libelle_Produit")]
        public EntityCollection<Libelle_Produit> Libelle_Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Libelle_Produit>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Libelle_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Libelle_Produit>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Libelle_Produit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Variation__Langa__0DAF0CB0", "T_Variation")]
        public EntityCollection<Variation> Variation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Variation>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Variation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Variation>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Variation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Libelle_Produit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Libelle_Produit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Libelle_Produit object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="langageId">Initial value of the LangageId property.</param>
        /// <param name="libelle">Initial value of the Libelle property.</param>
        public static Libelle_Produit CreateLibelle_Produit(global::System.String sku, global::System.Int32 langageId, global::System.String libelle)
        {
            Libelle_Produit libelle_Produit = new Libelle_Produit();
            libelle_Produit.Sku = sku;
            libelle_Produit.LangageId = langageId;
            libelle_Produit.Libelle = libelle;
            return libelle_Produit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LangageId
        {
            get
            {
                return _LangageId;
            }
            set
            {
                if (_LangageId != value)
                {
                    OnLangageIdChanging(value);
                    ReportPropertyChanging("LangageId");
                    _LangageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LangageId");
                    OnLangageIdChanged();
                }
            }
        }
        private global::System.Int32 _LangageId;
        partial void OnLangageIdChanging(global::System.Int32 value);
        partial void OnLangageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Libelle_P__Langa__2D27B809", "T_Langue")]
        public Langue Langue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Langue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Langue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Langue> LangueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Langue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Langue>("HDIProductDBModel.FK__Libelle_P__Langa__2D27B809", "T_Langue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Prix")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prix : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Prix object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="date_debut">Initial value of the Date_debut property.</param>
        /// <param name="date_fin">Initial value of the Date_fin property.</param>
        public static Prix CreatePrix(global::System.String sku, global::System.DateTime date_debut, global::System.DateTime date_fin)
        {
            Prix prix = new Prix();
            prix.Sku = sku;
            prix.Date_debut = date_debut;
            prix.Date_fin = date_fin;
            return prix;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_debut
        {
            get
            {
                return _Date_debut;
            }
            set
            {
                if (_Date_debut != value)
                {
                    OnDate_debutChanging(value);
                    ReportPropertyChanging("Date_debut");
                    _Date_debut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date_debut");
                    OnDate_debutChanged();
                }
            }
        }
        private global::System.DateTime _Date_debut;
        partial void OnDate_debutChanging(global::System.DateTime value);
        partial void OnDate_debutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_fin
        {
            get
            {
                return _Date_fin;
            }
            set
            {
                if (_Date_fin != value)
                {
                    OnDate_finChanging(value);
                    ReportPropertyChanging("Date_fin");
                    _Date_fin = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date_fin");
                    OnDate_finChanged();
                }
            }
        }
        private global::System.DateTime _Date_fin;
        partial void OnDate_finChanging(global::System.DateTime value);
        partial void OnDate_finChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prix_produit
        {
            get
            {
                return _Prix_produit;
            }
            set
            {
                OnPrix_produitChanging(value);
                ReportPropertyChanging("Prix_produit");
                _Prix_produit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prix_produit");
                OnPrix_produitChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prix_produit;
        partial void OnPrix_produitChanging(Nullable<global::System.Decimal> value);
        partial void OnPrix_produitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type_promo
        {
            get
            {
                return _Type_promo;
            }
            set
            {
                OnType_promoChanging(value);
                ReportPropertyChanging("Type_promo");
                _Type_promo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type_promo");
                OnType_promoChanged();
            }
        }
        private global::System.String _Type_promo;
        partial void OnType_promoChanging(global::System.String value);
        partial void OnType_promoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Prix__Sku__1367E606", "T_Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Produit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Produit object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="rangeId">Initial value of the RangeId property.</param>
        public static Produit CreateProduit(global::System.String sku, global::System.Int32 rangeId)
        {
            Produit produit = new Produit();
            produit.Sku = sku;
            produit.RangeId = rangeId;
            return produit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Int32> _Length;
        partial void OnLengthChanging(Nullable<global::System.Int32> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int32> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private Nullable<global::System.Int32> _Volume;
        partial void OnVolumeChanging(Nullable<global::System.Int32> value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RangeId
        {
            get
            {
                return _RangeId;
            }
            set
            {
                OnRangeIdChanging(value);
                ReportPropertyChanging("RangeId");
                _RangeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RangeId");
                OnRangeIdChanged();
            }
        }
        private global::System.Int32 _RangeId;
        partial void OnRangeIdChanging(global::System.Int32 value);
        partial void OnRangeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Self_Assembly
        {
            get
            {
                return _Self_Assembly;
            }
            set
            {
                OnSelf_AssemblyChanging(value);
                ReportPropertyChanging("Self_Assembly");
                _Self_Assembly = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Self_Assembly");
                OnSelf_AssemblyChanged();
            }
        }
        private global::System.String _Self_Assembly;
        partial void OnSelf_AssemblyChanging(global::System.String value);
        partial void OnSelf_AssemblyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Statut
        {
            get
            {
                return _Statut;
            }
            set
            {
                OnStatutChanging(value);
                ReportPropertyChanging("Statut");
                _Statut = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Statut");
                OnStatutChanged();
            }
        }
        private global::System.String _Statut;
        partial void OnStatutChanging(global::System.String value);
        partial void OnStatutChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Description__Sku__1920BF5C", "Description_Dgccrf")]
        public EntityCollection<Description_Dgccrf> Description_Dgccrf
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Description_Dgccrf>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "Description_Dgccrf");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Description_Dgccrf>("HDIProductDBModel.FK__Description__Sku__1920BF5C", "Description_Dgccrf", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Description__Sku__1ED998B2", "Description_Plus")]
        public EntityCollection<Description_Plus> Description_Plus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Description_Plus>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "Description_Plus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Description_Plus>("HDIProductDBModel.FK__Description__Sku__1ED998B2", "Description_Plus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Libelle_Pro__Sku__2E1BDC42", "T_Libelle_Produit")]
        public EntityCollection<Libelle_Produit> Libelle_Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Libelle_Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Libelle_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Libelle_Produit>("HDIProductDBModel.FK__Libelle_Pro__Sku__2E1BDC42", "T_Libelle_Produit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Prix__Sku__1367E606", "T_Prix")]
        public EntityCollection<Prix> Prix
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Prix>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Prix");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Prix>("HDIProductDBModel.FK__Prix__Sku__1367E606", "T_Prix", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Produit__RangeId__0519C6AF", "T_Range")]
        public Range Range
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Range>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Range").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Range>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Range").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Range> RangeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Range>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Range");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Range>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Range", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Variation__Sku__0EA330E9", "T_Variation")]
        public EntityCollection<Variation> Variation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Variation>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Variation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Variation>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Variation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "Produit_Impression", "Format_Impression")]
        public EntityCollection<Format_Impression> Format_Impression
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Format_Impression>("HDIProductDBModel.Produit_Impression", "Format_Impression");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Format_Impression>("HDIProductDBModel.Produit_Impression", "Format_Impression", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Range")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Range : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Range object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Range CreateRange(global::System.Int32 id)
        {
            Range range = new Range();
            range.Id = id;
            return range;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RangeName
        {
            get
            {
                return _RangeName;
            }
            set
            {
                OnRangeNameChanging(value);
                ReportPropertyChanging("RangeName");
                _RangeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RangeName");
                OnRangeNameChanged();
            }
        }
        private global::System.String _RangeName;
        partial void OnRangeNameChanging(global::System.String value);
        partial void OnRangeNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Produit__RangeId__0519C6AF", "T_Produit")]
        public EntityCollection<Produit> Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produit>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produit>("HDIProductDBModel.FK__Produit__RangeId__0519C6AF", "T_Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="resultats_recherche")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resultats_recherche : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resultats_recherche object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="variationName">Initial value of the VariationName property.</param>
        /// <param name="libelle">Initial value of the Libelle property.</param>
        /// <param name="date_debut">Initial value of the Date_debut property.</param>
        /// <param name="date_fin">Initial value of the Date_fin property.</param>
        public static resultats_recherche Createresultats_recherche(global::System.String sku, global::System.String variationName, global::System.String libelle, global::System.DateTime date_debut, global::System.DateTime date_fin)
        {
            resultats_recherche resultats_recherche = new resultats_recherche();
            resultats_recherche.Sku = sku;
            resultats_recherche.VariationName = variationName;
            resultats_recherche.Libelle = libelle;
            resultats_recherche.Date_debut = date_debut;
            resultats_recherche.Date_fin = date_fin;
            return resultats_recherche;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RangeName
        {
            get
            {
                return _RangeName;
            }
            set
            {
                OnRangeNameChanging(value);
                ReportPropertyChanging("RangeName");
                _RangeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RangeName");
                OnRangeNameChanged();
            }
        }
        private global::System.String _RangeName;
        partial void OnRangeNameChanging(global::System.String value);
        partial void OnRangeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VariationName
        {
            get
            {
                return _VariationName;
            }
            set
            {
                if (_VariationName != value)
                {
                    OnVariationNameChanging(value);
                    ReportPropertyChanging("VariationName");
                    _VariationName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VariationName");
                    OnVariationNameChanged();
                }
            }
        }
        private global::System.String _VariationName;
        partial void OnVariationNameChanging(global::System.String value);
        partial void OnVariationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                if (_Libelle != value)
                {
                    OnLibelleChanging(value);
                    ReportPropertyChanging("Libelle");
                    _Libelle = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Libelle");
                    OnLibelleChanged();
                }
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prix_produit
        {
            get
            {
                return _Prix_produit;
            }
            set
            {
                OnPrix_produitChanging(value);
                ReportPropertyChanging("Prix_produit");
                _Prix_produit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prix_produit");
                OnPrix_produitChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prix_produit;
        partial void OnPrix_produitChanging(Nullable<global::System.Decimal> value);
        partial void OnPrix_produitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_debut
        {
            get
            {
                return _Date_debut;
            }
            set
            {
                if (_Date_debut != value)
                {
                    OnDate_debutChanging(value);
                    ReportPropertyChanging("Date_debut");
                    _Date_debut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date_debut");
                    OnDate_debutChanged();
                }
            }
        }
        private global::System.DateTime _Date_debut;
        partial void OnDate_debutChanging(global::System.DateTime value);
        partial void OnDate_debutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_fin
        {
            get
            {
                return _Date_fin;
            }
            set
            {
                if (_Date_fin != value)
                {
                    OnDate_finChanging(value);
                    ReportPropertyChanging("Date_fin");
                    _Date_fin = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date_fin");
                    OnDate_finChanged();
                }
            }
        }
        private global::System.DateTime _Date_fin;
        partial void OnDate_finChanging(global::System.DateTime value);
        partial void OnDate_finChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statut
        {
            get
            {
                return _statut;
            }
            set
            {
                OnstatutChanging(value);
                ReportPropertyChanging("statut");
                _statut = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statut");
                OnstatutChanged();
            }
        }
        private global::System.String _statut;
        partial void OnstatutChanging(global::System.String value);
        partial void OnstatutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryCode
        {
            get
            {
                return _CountryCode;
            }
            set
            {
                OnCountryCodeChanging(value);
                ReportPropertyChanging("CountryCode");
                _CountryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryCode");
                OnCountryCodeChanged();
            }
        }
        private global::System.String _CountryCode;
        partial void OnCountryCodeChanging(global::System.String value);
        partial void OnCountryCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HDIProductDBModel", Name="T_Variation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Variation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Variation object.
        /// </summary>
        /// <param name="sku">Initial value of the Sku property.</param>
        /// <param name="langageId">Initial value of the LangageId property.</param>
        /// <param name="variationName">Initial value of the VariationName property.</param>
        public static Variation CreateVariation(global::System.String sku, global::System.Int32 langageId, global::System.String variationName)
        {
            Variation variation = new Variation();
            variation.Sku = sku;
            variation.LangageId = langageId;
            variation.VariationName = variationName;
            return variation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sku
        {
            get
            {
                return _Sku;
            }
            set
            {
                if (_Sku != value)
                {
                    OnSkuChanging(value);
                    ReportPropertyChanging("Sku");
                    _Sku = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sku");
                    OnSkuChanged();
                }
            }
        }
        private global::System.String _Sku;
        partial void OnSkuChanging(global::System.String value);
        partial void OnSkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LangageId
        {
            get
            {
                return _LangageId;
            }
            set
            {
                if (_LangageId != value)
                {
                    OnLangageIdChanging(value);
                    ReportPropertyChanging("LangageId");
                    _LangageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LangageId");
                    OnLangageIdChanged();
                }
            }
        }
        private global::System.Int32 _LangageId;
        partial void OnLangageIdChanging(global::System.Int32 value);
        partial void OnLangageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VariationName
        {
            get
            {
                return _VariationName;
            }
            set
            {
                OnVariationNameChanging(value);
                ReportPropertyChanging("VariationName");
                _VariationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VariationName");
                OnVariationNameChanged();
            }
        }
        private global::System.String _VariationName;
        partial void OnVariationNameChanging(global::System.String value);
        partial void OnVariationNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Variation__Langa__0DAF0CB0", "T_Langue")]
        public Langue Langue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Langue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Langue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Langue> LangueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Langue>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Langue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Langue>("HDIProductDBModel.FK__Variation__Langa__0DAF0CB0", "T_Langue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HDIProductDBModel", "FK__Variation__Sku__0EA330E9", "T_Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("HDIProductDBModel.FK__Variation__Sku__0EA330E9", "T_Produit", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
